#Global rate of emissions for all pollutants and sources on the server
#Range: 0.0 ~ 10.0
globalEmissionRate = 1.0
#Experience gain after replacing the filter material in a respirator or a vacuum bag
#Range: -10 ~ 10
filterReplacingExpGain = 0

[GasExplosions]
	#The way ignited gas explosion affects surrounding blocks
	#Allowed Values: NONE, BREAK, DESTROY
	blockInteraction = "BREAK"
	#Maximum gas blocks that can be involved in an explosive chain reaction
	#Range: 0 ~ 2048
	maxChainLength = 512

[EmissionSources]
	#Rate of emissions from this source
	#Range: 0.0 ~ 10.0
	Breakables = 1.0
	#Rate of emissions from this source
	#Range: 0.0 ~ 10.0
	Entities = 1.0
	#Rate of emissions from this source
	#Range: 0.0 ~ 10.0
	WallTorches = 0.0
	#Rate of emissions from this source
	#Range: 0.0 ~ 10.0
	DroppedTorches = 0.0
	#Rate of emissions from this source
	#Range: 0.0 ~ 10.0
	Campfires = 0.0
	#Rate of emissions from this source
	#Range: 0.0 ~ 10.0
	BurntItems = 1.0
	#Enables / disables emissions from this source
	Furnaces = true
	#Enables / disables emissions from this source
	BurntBlocks = true
	#Enables / disables emissions from this source
	Explosion = true
	#Enables / disables emissions from this source
	HostileMobDeath = true
	#Enables / disables emissions from this source
	LavaTouchingWater = true
	#Enables / disables emissions from this source
	PlayerDeath = true
	#Enables / disables emissions from this source
	AnimalFeeding = true
	#Enables / disables emissions from this source
	AnimalDeath = true
	#Enables / disables emissions from this source
	PlayerEating = true

	[EmissionSources.Mods]
		#Rate of emissions from this source
		#Range: 0.0 ~ 10.0
		ImmersiveVehicles = 1.0
		#Enables / disables emissions from this source
		CreateInWorldProcessing = true

