name = "Season 6 1.20"
author = "Maple Modworks"
version = "cc66e12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b71b01768c6c7ed8c8b35a7aee71aebc2e1f3a66a33d358fd6c6419f7977f52"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
