name = "Aeronautics Shenanigans"
author = "Maple Modworks"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b597b762897df7b572fb0520780980e64eebb4c6446801cf2af095773671355"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
